# Visualization
RED = (255, 0 , 0)

# Simulator
START_CLUSTERED = False
NUM_FISH = 50
NUM_PREDATORS = 2
WORLD_SIZE = (300, 150)
FREQUENCY = 200

# Pygame
SQUARE_SIZE = 5

# Predator
PREDATOR_SPEED = 1
PREDATOR_ACCEL = 0.014
PREDATOR_SIZE = 1;
PREDATOR_SENSING_DISTANCE = 30

# Fish
FISH_SPEED = 0.6
FISH_ACCEL = 0.06
FISH_SIZE = 0.5;
FISH_SENSING_DISTANCE = 20

# Flock
FISH_DESIRED_DIST = 7
FISH_NEIGHBOR_FORCE = FISH_ACCEL/4
